---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: livewall-apiserver
  name: livewall-silence
  namespace: default
spec:
  ports:
  - ClusterIP:
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: livewall-apiserver
  sessionAffinity: None
  type: ClusterIP