---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: livewall-event
  name: livewall-event
  namespace: default
spec:
  ports:
  - ClusterIP:
    port: 5002
    protocol: TCP
    targetPort: 5002
  selector:
    run: livewall-event
  sessionAffinity: None
  type: ClusterIP
