---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: livewall-frontend
  name: livewall-frontend
  namespace: default
spec:
  ports:
  - LoadBalancer:
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: livewall-frontend
  sessionAffinity: None
  type: LoadBalancer
