---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: livewall-incident
  name: livewall-incident
  namespace: default
spec:
  ports:
  - ClusterIP:
    port: 5003
    protocol: TCP
    targetPort: 5003
  selector:
    run: livewall-incident
  sessionAffinity: None
  type: ClusterIP
