---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: livewall-incident
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: livewall-incident
    spec:
      containers:
      - env:
        - name: appd_appname
          value: "livewall-yaml"
        - name: appd_tiername
          value: "incident"
        - name: appd_hostname
          value: "192.168.130.210"
        - name: appd_port
          value: "8090"
        - name: appd_sslenabled
          value: "false"
        - name: appd_account
          value: "GREMLINS"
        - name: appd_accesskey
          value: "9e3b433c-d509-4ea1-bb3b-05409a5aab24"
        - name: db_host
          value: "10.139.11.209"
        - name: db_user
          value: "falcon"
        - name: db_pass
          value: "C1sco123"
        - name: db_database
          value: "predator"
        - name: bing_maps_api_key
          value: "AuqW9LUO744wxmr6ik0PiJYAGbtKqmelkReiUT5_jhP4Dgh4cwDH-m9vE5wLY2z3"
        image: 10.139.12.210/cl-wall/incident:latest
        name: livewall-incident
