---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: livewall-weather
  name: livewall-weather
  namespace: default
spec:
  ports:
  - ClusterIP:
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    run: livewall-weather
  sessionAffinity: None
  type: ClusterIP
